name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: node:lts-alpine

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm ci

      - name: Lint code
        run: npm run lint

      - name: Build code
        run: npm run build

      # Uncomment the following lines once you add tests to the repo
      # - name: Run tests
      #   run: npm run test
